# Generated by Django 3.2.5 on 2021-08-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='menu_logos/', verbose_name='Логотип заведения'),
        ),
    ]
