# Generated by Django 3.2.5 on 2021-09-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_menu_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='instagram',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Инстаграм:'),
        ),
    ]
