# Generated by Django 3.2.5 on 2021-09-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_menu_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='logo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='menu_logos', verbose_name='Логотип заведения'),
        ),
    ]
