# Generated by Django 3.2.5 on 2021-09-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subsctiption',
            field=models.CharField(choices=[('None', 'Нет'), ('Casual', 'Обычная')], default='None', max_length=20),
        ),
    ]
