# Generated by Django 3.2.5 on 2021-09-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_subsctiption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='subsctiption',
        ),
        migrations.AddField(
            model_name='customer',
            name='subscription',
            field=models.CharField(choices=[('None', 'Нет'), ('Casual', 'Обычная')], default='None', max_length=20, verbose_name='Подписка'),
        ),
    ]
