# Generated by Django 3.2.5 on 2021-10-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210906_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
