# Generated by Django 3.2.5 on 2021-10-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_is_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_email_confirmed',
        ),
    ]
